[build]
  # Skip the build process - we're deploying pre-built files
  command = "echo 'No build needed'"
  publish = "."
  ignore = "/bin/true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200