[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18"
  
# Increase build timeout and memory
[build.processing]
  skip_processing = false

# Add build optimizations for large JS bundles
[[build.environment]]
  NODE_OPTIONS = "--max-old-space-size=4096"

# Prevent timeout on large builds
[build]
  command = "npm ci --legacy-peer-deps && npm run build"