[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"
  
# Increase build timeout and memory
[build.processing]
  skip_processing = false